name: 🚀 Build & Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v6

      - name: 🛠️ Setup Swift
        uses: swift-actions/setup-swift@v3
        with:
          swift-version: "6.3"

      - name: 📦 Resolve Swift dependencies
        run: swift package resolve

      - name: 🛠️ Build
        run: swift build

      - name: 🧪 Test
        run: swift test --parallel
